// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IqIveqU8SXYOjPAkwVNUECzoRK1c_Kk',
    appId: '1:442119640005:web:005762d9bcca2a8f73b1ac',
    messagingSenderId: '442119640005',
    projectId: 'stride-1f42a',
    authDomain: 'stride-1f42a.firebaseapp.com',
    storageBucket: 'stride-1f42a.firebasestorage.app',
    measurementId: 'G-3R4XGMEX64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGLSzFU_kAzqRSV5p1o7z4XkVRVaxJT4',
    appId: '1:442119640005:android:49fd730b713b566273b1ac',
    messagingSenderId: '442119640005',
    projectId: 'stride-1f42a',
    storageBucket: 'stride-1f42a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-IqIveqU8SXYOjPAkwVNUECzoRK1c_Kk',
    appId: '1:442119640005:web:b80e794396506c1873b1ac',
    messagingSenderId: '442119640005',
    projectId: 'stride-1f42a',
    authDomain: 'stride-1f42a.firebaseapp.com',
    storageBucket: 'stride-1f42a.firebasestorage.app',
    measurementId: 'G-C1T5G7MFRN',
  );
}
